stages:
- name: build
  steps:
  - runScriptConfig:
      image: https://hub.docker.com/r/zhuzhu/gradle-jdk8-alpine
      shellScript: |-
        chmod +x ./aicode/gradlew
        ./aicode/gradlew :aicode:build -x test
        ls -alh *
  - publishImageConfig:
      dockerfilePath: ./aicode/Dockerfile
      buildContext: .
      tag: aicode/test
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./aicode/k8s/aicode.yml
timeout: 60
notification: {}
