stages:
- name: build
  steps:
  - runScriptConfig:
      image: gradle:jdk8
      shellScript: gradle build
  - publishImageConfig:
      dockerfilePath: ./aicode/Dockerfile
      buildContext: .
      tag: aicode/test
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./aicode/k8s/aicode.yml
timeout: 60
notification: {}
