stages:
- name: build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |
        ls -alh
        echo "\n\n\n"
        echo "pipeline id : ${CICD_PIPELINE_ID}"
        echo "build number: $BUILD_NUMBER"
        echo "git tag : ${CICD_GIT_TAG}"
        echo "git branch : ${CICD_GIT_BRANCH}"
        echo "seq: ${CICD_EXECUTION_SEQUENCE}"
        echo "repo name: ${CICD_GIT_REPO_NAME}"
        echo "\n\n\n"
        chmod 777 -Rf *
        pwd
        chmod +x aicode/gradlew
        ./aicode/gradlew clean :build -x test
  - publishImageConfig:
      dockerfilePath: ./aicode/Dockerfile
      buildContext: .
      tag: aicode/test
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./aicode/k8s/aicode.yml
timeout: 60
notification: {}
