stages:
- name: build
  steps:
  - runScriptConfig:
      image: csdmdev/gradle6-jdk11
      shellScript: |-
        ls -alh
        gradle --verison
        gradle build
        ls -alh *
  - publishImageConfig:
      dockerfilePath: ./aicode/Dockerfile
      buildContext: .
      tag: aicode/test
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./aicode/k8s/aicode.yml
timeout: 60
notification: {}
