stages:
- name: build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |
        ls -alh *
        chmod 777 aicode/gradlew
        aicode/gradlew clean
        aicode/gradlew :aicode:build -x test
  - publishImageConfig:
      dockerfilePath: ./aicode/Dockerfile
      buildContext: .
      tag: aicode/test
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./aicode/k8s/aicode.yml
timeout: 60
notification: {}
