stages:
- name: build
  steps:
  - runScriptConfig:
      image: gradle:jdk8
      shellScript: |-
        pwd
        chmod 777 -Rf *
        ls -alh *
        cd aicode
        pwd
        gradle :aicode:build -x test
  - publishImageConfig:
      dockerfilePath: ./aicode/Dockerfile
      buildContext: .
      tag: aicode/test
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./aicode/k8s/aicode.yml
timeout: 60
notification: {}
