version: '2'

services:
  aicode-db:
    image: hegaoye/mysql:1.0-beta
    hostname: aicode-db
    ports:
      - "3306:3306"
    command: [
      '--lower_case_table_names=1'
    ]
    environment:
       MYSQL_ROOT_PASSWORD: aicode
    restart: always
    container_name: aicode-db

  aicode:
     image: hegaoye/aicode:1.0-beta
     links:
         - aicode-db
     ports:
        - "8080:8080"
     environment:
       host: "aicode-db:3306"
       username: root
       password: aicode
     depends_on:
            - aicode-db
     restart: always
     container_name: aicode