---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aicode-demo
  labels:
    app: aicode-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aicode-demo
      component: ks-aicode-dev
      tier: backend
  template:
    metadata:
      labels:
        app: aicode-demo
        component: ks-aicode-dev
        tier: backend
    spec:
      containers:
        - name: aicode-demo
          image: hegaoye/aicode:latest
#          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
          ports:
            - containerPort: 8080
          env:
            - name: host
              value: "mysql:3306"
            - name: username
              value: "root"
            - name: password
              value: "mysqladmin"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: aicode-demo
    component: ks-aicode-dev
  name: aicode-demo-svc
  namespace: aicode-dev
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30888
  type: NodePort
  selector:
    app: aicode-demo
    component: ks-aicode-dev
    tier: backend