apiVersion: apps/v1
kind: Deployment
metadata:
  name: aicode
  labels:
    app: aicode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aicode-demo
      component: ks-aicode-dev
      tier: backend
  template:
    metadata:
      labels:
        app: aicode-demo
        component: ks-aicode-dev
        tier: backend
    spec:
      containers:
        - name: aicode-demo
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: host
              value: "mysql:3306" #对应db的service 名和开放的端口号 默认是3306
            - name: username
              value: "root"
            - name: password
              value: "mysqladmin"  # 数据库的密码 对应db中设置的
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: aicode-demo
    component: ks-aicode-dev
  name: aicode-demo-svc
  namespace: aicode-dev
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30888
  type: NodePort
  selector:
    app: aicode-demo
    component: ks-aicode-dev
    tier: backend